
use crate::ast::{
    SqlStmt, CreateDatasetStmt, DropDatasetStmt, RelDef, RelElt, SelectStmt, InsertIntoStmt,
    UpdateStmt, DeleteFromStmt,  FromListItem, Predicate, Member,
    MemberPart, ConstValue, PathSegments, PathSegment, FieldSegments, PredLogicOperator, ArithOperator,
    CompOperator, UpdateOp, SetValue, AlterAction, AlterDatasetStmt, IndexDef, IndexType,
    DescribeDatasetStmt, append_jsonpath, RelUpdate, RelsUpdate, ValRels, UpdateAction
};

use crate::SqlParseError;

use crate::lexer;
//use crate::lexer::{Lexer, Tok, Location, LexicalError};
use crate::lexer::Tok;
use lalrpop_util::ParseError;

// Parser expects tokens of shape: (usize, Tok, usize)
// Example of calling the generated parser:
// let mut lexer = crate::lexer::Lexer::new(input);
// let tokens = std::iter::from_fn(|| lexer.next());
// parser::SqlStmtParser::new().parse(tokens)

grammar;

extern {
    type Location = usize;
    type Error = lexer::LexicalError;

    enum Tok {
        // Terminals coming from the lexer Tok enum
        "CREATE" => lexer::Tok::Create,
        "DROP" => lexer::Tok::Drop,
        "DESCRIBE" => lexer::Tok::Describe,
        "ALTER" => lexer::Tok::Alter,
        "ADD" => lexer::Tok::Add,
        "DATASET" => lexer::Tok::Dataset,
        "RELATIONSHIP" => lexer::Tok::Relationship,
        "INVERSE" => lexer::Tok::Inverse,
        "PRIMARY" => lexer::Tok::Primary,
        "KEY" => lexer::Tok::Key,
        "UNIQUE" => lexer::Tok::Unique,
        "INDEX" => lexer::Tok::Index,
        "INSERT" => lexer::Tok::Insert,
        "DELETE" => lexer::Tok::Delete,
        "REMOVE" => lexer::Tok::Remove,
        "UPDATE" => lexer::Tok::Update,
        "CLEAR" => lexer::Tok::Clear,
        "SET" => lexer::Tok::Set,
        "INTO" => lexer::Tok::Into,
        "VALUES" => lexer::Tok::Values,
        "SELECT" => lexer::Tok::Select,
        "FROM" => lexer::Tok::From,
        "AS" => lexer::Tok::As,
        "IS" => lexer::Tok::Is,
        "NOT" => lexer::Tok::Not,
        "NULL" => lexer::Tok::Null,
        "WHERE" => lexer::Tok::Where,
        "AND" => lexer::Tok::And,
        "OR" => lexer::Tok::Or,
        "IN" => lexer::Tok::In,
        "LIKE" => lexer::Tok::Like,
        "REGEXP" => lexer::Tok::Regexp,
        "+" => lexer::Tok::Plus,
        "-" => lexer::Tok::Minus,
        "*" => lexer::Tok::Multiply,
        "/" => lexer::Tok::Divide,
        "=" => lexer::Tok::Eq,
        "==" => lexer::Tok::EqEq,
        "<>" => lexer::Tok::Ne,
        ">" => lexer::Tok::Gt,
        "<" => lexer::Tok::Lt,
        ">=" => lexer::Tok::Ge,
        "<=" => lexer::Tok::Le,
        "." => lexer::Tok::Dot,
        "," => lexer::Tok::Comma,
        "$" => lexer::Tok::Dollar,
        "@" => lexer::Tok::Arobas,
        "?" => lexer::Tok::QuestionMark,
        "(" => lexer::Tok::OpenBracket,
        ")" => lexer::Tok::CloseBracket,
        "[" => lexer::Tok::OpenSqBracket,
        "]" => lexer::Tok::CloseSqBracket,
        "ident" => lexer::Tok::Ident(<String>),
        "bool" => lexer::Tok::Bool(<bool>),
        "number" => lexer::Tok::Number(<String>),
        "integer" => lexer::Tok::Integer(<String>),
        "singlequotedstring" => lexer::Tok::SingleQuotedString(<String>),
        "doublequotedstring" => lexer::Tok::DoubleQuotedString(<String>),
        "lexerror" => lexer::Tok::LexError(<String>),
    }
}

pub SqlStmtExpr: SqlStmt = {
    <stmt:CreateDatasetExpr> => stmt,
    <stmt:DropDatasetExpr> => stmt,
    <stmt:DescribeDatasetExpr> => stmt,
    <stmt:AlterDatasetExpr> => stmt,
    <stmt:InsertIntoExpr> => stmt,
    <stmt:DeleteFromExpr> => stmt,
    <stmt:UpdateExpr> => stmt,
    <stmt:DeleteFromWhereExpr> => stmt,
    <stmt:SelectProjExpr> => stmt,
    <stmt:SelectFromExpr> => stmt,
    <stmt:SelectFromWhereExpr> => stmt,
}

// CREATE DATASET xxx;
CreateDatasetExpr: SqlStmt = {
    // CREATE DATASET ds PRIMARY KEY (a, b) RELATIONSHIP rel(tgt) ...;
    "CREATE" "DATASET" <ds_name:"ident"> <actions:SpaceSep<CreateActionExpr>> => {
        SqlStmt::CreateDataset(
            CreateDatasetStmt {
                name: ds_name,
                actions: actions,
            }
        )
    }
}

CreateActionExpr: AlterAction = {
    "RELATIONSHIP" <rel:"ident"> "(" <tgtds:"ident"> ")" => {
        AlterAction::AddRel(
            RelDef {
                update_type: UpdateOp::DdlAdd,
                name: rel,
                tgt_dataset: tgtds,
            }
        )
    },
    "PRIMARY" "KEY" "(" <f:CommaSep<FieldSegsExpr>> ")" => {
        AlterAction::AddIdx(
            IndexDef {
                name: "".to_string(),
                idx_type: IndexType::Pkey,
                update_type: UpdateOp::DdlAdd,
                fields: f,
            }
        )
    },
    "INDEX" <n:"ident"> "(" <fields:CommaSep<FieldSegsExpr>> ")" => {
        AlterAction::AddIdx(
            IndexDef {
                name: n,
                idx_type: IndexType::NonUnique,
                update_type: UpdateOp::DdlAdd,
                fields: fields,
            }
        )
    },
    "UNIQUE" "INDEX" <n:"ident"> "(" <fields:CommaSep<FieldSegsExpr>> ")" => {
        AlterAction::AddIdx(
            IndexDef {
                name: n,
                idx_type: IndexType::Unique,
                update_type: UpdateOp::DdlAdd,
                fields: fields,
            }
        )
    }
}


// DROP DATASET ds;
DropDatasetExpr: SqlStmt = {
    "DROP" "DATASET" <ds_name:"ident"> => {
        let stmt = SqlStmt::DropDataset(
            DropDatasetStmt {
                name: ds_name,
            }
        );
        stmt
    }
}

// DESCRIBE DATASET ds;
DescribeDatasetExpr: SqlStmt = {
    "DESCRIBE" "DATASET" <ds_name:"ident"> => {
        let stmt = SqlStmt::DescribeDataset(
            DescribeDatasetStmt {
                name: ds_name,
            }
        );
        stmt
    }
}

// ALTER DATASET ds DROP RELATIONSHIP rel, ADD RELATIONSHIP rel(tgtds), ...
AlterDatasetExpr: SqlStmt = {
    "ALTER" "DATASET" <name:"ident"> <acts:SpaceSep<AlterActionExpr>> => {
        let stmt = SqlStmt::AlterDataset(
            AlterDatasetStmt {
                ds_name: name,
                actions: acts,
            }
        );
        stmt
    }
}

AlterActionExpr: AlterAction = {
    "ADD" "RELATIONSHIP" <rel:"ident"> "(" <tgtds:"ident"> ")" => {
        let action = AlterAction::AddRel(
            RelDef {
                update_type: UpdateOp::DdlAdd,
                name: rel,
                tgt_dataset: tgtds,
            }
        );
        action
    },
    "DROP" "RELATIONSHIP" <rel:"ident"> => {
        AlterAction::DropRel(rel)
    },
    "ADD" "PRIMARY" "KEY" "(" <fields:CommaSep<FieldSegsExpr>> ")" => {
        AlterAction::AddIdx(
            IndexDef {
                name: "".to_string(),
                idx_type: IndexType::Pkey,
                update_type: UpdateOp::DdlAdd,
                fields: fields,
            }
        )
    },
    "DROP" "PRIMARY" "KEY" => {
        AlterAction::DropIdx("".to_string())
    },
    "DROP" "INDEX" <n:"ident"> => {
        AlterAction::DropIdx(n)
    },
    "ADD" "INDEX" <n:"ident"> "(" <fields:CommaSep<FieldSegsExpr>> ")" => {
        AlterAction::AddIdx(
            IndexDef {
                name: n,
                idx_type: IndexType::NonUnique,
                update_type: UpdateOp::DdlAdd,
                fields: fields,
            }
        )
    },
    "ADD" "UNIQUE" "INDEX" <n:"ident"> "(" <fields:CommaSep<FieldSegsExpr>> ")" => {
        AlterAction::AddIdx(
            IndexDef {
                name: n,
                idx_type: IndexType::Unique,
                update_type: UpdateOp::DdlAdd,
                fields: fields,
            }
        )
    }
}

DeleteFromWhereExpr: SqlStmt = {
    <stmt:DeleteFromExpr> "WHERE" <pred_list:PredicateListExpr> => {
        let SqlStmt::DeleteFrom(del_stmt) = stmt else { panic!("missing from expr") };
        let stmt = SqlStmt::DeleteFrom(
            DeleteFromStmt {
                predicate_list: pred_list,
                ..del_stmt
            }
        );
        stmt
    }
}

DeleteFromExpr: SqlStmt = {
   // DELETE FROM dataset WHERE ....
   "DELETE" "FROM" <ds_name:"ident"> => {
        let stmt = SqlStmt::DeleteFrom(
            DeleteFromStmt {
                ds_name: ds_name,
                predicate_list: vec![],
            }
        );
        stmt
   },
}

UpdateExpr: SqlStmt = {
    // UPDATE dataset SET a = '..', b.c = '..'
    "UPDATE" <ds:"ident"> <acts:SpaceSep<UpdateActionsExpr>> "WHERE" <preds:PredicateListExpr> => {
        let stmt = SqlStmt::Update(
            UpdateStmt {
                ds_name: ds,
                actions: acts,
                predicate_list: preds,
            }
        );
        stmt
    },
}

UpdateActionsExpr: UpdateAction = {
    // SET a = '..'  b.c = '..'
    "SET" <svals:SpaceSep<SetValueExpr>> => {
        UpdateAction {
          delelts: vec![],
          setvals: svals,
          updrels: vec![],
        }
    },
    // DELETE a, b.c
    "DELETE" <d:SpaceSep<FieldSegsExpr>> => {
        UpdateAction {
          delelts: d,
          setvals: vec![],
          updrels: vec![],
        }
    },
    // INSERT r1 (a,b) (...) r2 (c,d) ...
    "INSERT" <ur:SpaceSep<RelUpdateExpr>> => {
        UpdateAction {
          delelts: vec![],
          setvals: vec![],
          updrels: vec![
            RelsUpdate {
                op: UpdateOp::Insert,
                rels: ur,
            }
          ],
        }
    },
    // REMOVE r1 (a,b) (...) r2 (c,d) ...
    "REMOVE" <ur:SpaceSep<RelUpdateExpr>> => {
        UpdateAction {
          delelts: vec![],
          setvals: vec![],
          updrels: vec![
            RelsUpdate {
                op: UpdateOp::Delete,
                rels: ur,
            }
          ],
        }
    },
    "CLEAR" <ur:SpaceSep<RelClearExpr>> => {
        UpdateAction {
          delelts: vec![],
          setvals: vec![],
          updrels: vec![
            RelsUpdate {
                op: UpdateOp::Clear,
                rels: ur,
            }
          ],
        } 
    }
}

InsertIntoExpr: SqlStmt = {
   // INSERT INTO dataset VALUES
   //   '{... v1 ...}' r1 (...) (...) r2 ... ,
   //   '{... v2 ...}' r3 ...
   "INSERT" "INTO" <ds_name:"ident"> "VALUES" <vrs:CommaSep<ValRelsExpr>> => {
        let stmt = SqlStmt::InsertInto(
            InsertIntoStmt {
                ds_name: ds_name,
                valsrels: vrs,
            }
        );
        stmt
    }
}

SelectFromWhereExpr: SqlStmt = {
    <stmt:SelectFromExpr> "WHERE" <pred_list:PredicateListExpr> => {
        let SqlStmt::Select(sel_stmt) = stmt else { panic!("missing from expr") };
        let stmt = SqlStmt::Select(
            SelectStmt {
                predicate_list: pred_list,
                ..sel_stmt
            }
        );
        stmt
    }
}

FromListItemExpr: FromListItem = {
    <dsname:"ident"> => FromListItem { ds_name: dsname, alias: None },
    <dsname:"ident"> <alias:"ident"> => FromListItem { ds_name: dsname, alias: Some(alias)}
}
    
SelectFromExpr: SqlStmt = {
    <stmt:SelectProjExpr> "FROM" <from_list:CommaSep<FromListItemExpr>> => {
        let SqlStmt::Select(sel_stmt) = stmt else { panic!("missing proj expr") };
        let stmt = SqlStmt::Select(
            SelectStmt {
                from_list: from_list,
                ..sel_stmt
            }
        );
        stmt
    },
    <stmt:SelectProjExpr> "FROM" "DATASET" => {
        let SqlStmt::Select(sel_stmt) = stmt else { panic!("missing proj expr") };
        let stmt = SqlStmt::Select(
            SelectStmt {
                from_list: vec![ FromListItem { ds_name: "dataset".to_string(), alias: None } ],
                ..sel_stmt
            }
        );
        stmt
    }
}

SelectProjExpr: SqlStmt = {
   "SELECT" <const_proj_list:ProjListExpr> => {
        let stmt = SqlStmt::Select(
            SelectStmt {
                proj_list: const_proj_list,
                from_list: vec![],
                predicate_list: vec![],
            }
        );
        stmt
    }
}

SetValueExpr: SetValue = {
    <p:FieldSegsExpr> "=" <c:ConstValueExpr> => {
        SetValue {
            fieldsegs: p,
            value: c,
        }
    },
}

PredicateListExpr: Vec<Predicate> = {
    <predicate:PredicateExpr> => vec![predicate],
    <predicate:PredicateExpr> <_predlogic:PredLogicExpr> <rest:PredicateListExpr> => {
        let mut v = vec![predicate];
        v.extend(rest);
        v
    },
};

PredicateExpr: Predicate = {
    <lpred:MemberStarExpr> <comp:PredCompOperExpr> <rpred:MemberStarExpr> => Predicate {
        left: lpred,
        right: rpred,
        comp_operator: comp,
    },
    <lpred:MemberStarExpr> "IS" "NULL" => Predicate {
        left: lpred,
        right: Member{ part: MemberPart::Value(ConstValue::IsNull()) },
        comp_operator: CompOperator::Eq,
    },
    <lpred:MemberStarExpr> "IS" "NOT" "NULL" => Predicate {
        left: lpred,
        right: Member{ part: MemberPart::Value(ConstValue::IsNull()) },
        comp_operator: CompOperator::Ne,
    },
    <lpred:MemberStarExpr> "IN" "(" <vals:CommaSep<ConstValueExpr>> ")" => {
        Predicate {
            left: lpred,
            right: Member{ part: MemberPart::ValueList(vals) },
            comp_operator: CompOperator::In,
        }
    },
    <lpred:MemberStarExpr> "NOT" "IN" "(" <vals:CommaSep<ConstValueExpr>> ")" => {
        Predicate {
            left: lpred,
            right: Member{ part: MemberPart::ValueList(vals) },
            comp_operator: CompOperator::NotIn,
        }
    },
    <lpred:MemberStarExpr> <c:StrCompOperExpr> <s:SingleQuotedStringExpr> => {
        Predicate {
            left: lpred,
            right: Member{ part: MemberPart::Value(ConstValue::SingleQuotedString(s)) },
            comp_operator: c,
        }
    },
}

StrCompOperExpr: CompOperator = {
    "LIKE" => CompOperator::Like,
    "NOT" "LIKE" => CompOperator::NotLike,
    "REGEXP" => CompOperator::Regexp,
    "NOT" "REGEXP" => CompOperator::NotRegexp,
}

JpathCompOperExpr: CompOperator = {
    "==" => CompOperator::EqEq,
    <CompOperExpr> => <>,
}

PredCompOperExpr: CompOperator = {
    "=" => CompOperator::Eq,
    <CompOperExpr> => <>,
}

CompOperExpr: CompOperator = {
    "<>" => CompOperator::Ne,
    ">" => CompOperator::Gt,
    "<" => CompOperator::Lt,
    ">=" => CompOperator::Ge,
    "<=" => CompOperator::Le,
}

PredLogicExpr: PredLogicOperator = {
    "AND" => PredLogicOperator::And,
    // TBD - later "OR" => PredLogicOperator::Or,
}

ProjListExpr: Vec<Member> = {
    <seglist:MemberStarExpr> => vec![seglist],
    <head:ProjListExpr> "," <path:MemberStarExpr> => {
        let mut v = head;
        v.push(path);
        v
    },
}

MemberStarExpr: Member = {
    StarPathSegsExpr => Member{ part: MemberPart::Path(<>) },
    MemberExpr,
}

MemberEltExpr: Member = {
    PathSegsMemberExpr => <>,
    ConstValueExpr => Member{ part: MemberPart::Value(<>) },
}

MemberExpr: Member = {
    <l:MemberExpr> <o:OperatorSymbExpr> <r:FactorExpr> => 
        Member{
            part: MemberPart::Tree(
                Box::new(l), 
                o, 
                Box::new(r),
            )
        },
    FactorExpr,
}

FactorExpr: Member = {
    <l:FactorExpr> "*" <r:MemberEltExpr> =>
        Member{
            part: MemberPart::Tree(
                Box::new(l), 
                ArithOperator::Multiply, 
                Box::new(r),
            )
        },
    <l:FactorExpr> "/" <r:MemberEltExpr> =>
        Member{
            part: MemberPart::Tree(
                Box::new(l), 
                ArithOperator::Divide, 
                Box::new(r),
            )
        },
    TermExpr,
}

TermExpr: Member = {
    MemberEltExpr,
    "(" <MemberExpr> ")"
}

PathSegsMemberExpr: Member = {
    PathSegsExpr => Member{ part: MemberPart::Path(<>) },
}

OperatorSymbExpr: ArithOperator = {
    "+" => ArithOperator::Plus,
    "-" => ArithOperator::Minus,
}

// Generic space separated list
SpaceSep<T>: Vec<T> = {
    <v:(<T>)*> => v
}

// Generic comma separated list
CommaSep<T>: Vec<T> = {
    <mut v:(<T> ",")*> <e:T> => {
        v.push(e);
        v
    }
}

// Generic dot separated list
DotSep<T>: Vec<T> = {
    <mut v:(<T> ".")*> <e:T> => {
        v.push(e);
        v
    }
}

FieldSegsExpr: FieldSegments = {
    DotSep<"ident"> => {
        FieldSegments{ segments: <> }
    }
}

PathSegsExpr: PathSegments = {
    <elt:PathElementExpr> => PathSegments { segments: vec![<>], jsonpath: vec![] },
    <head:PathSegsExpr> "." <elt:PathElementExpr> => {
        let mut v = head.segments;
        v.push(elt);
        PathSegments{ segments: v ,jsonpath: vec![] }
    },
}

// All path expressions, including '*' and jsonpath
StarPathSegsExpr: PathSegments = {
    <JsonPathExpr> => {
        append_jsonpath(PathSegments {segments: vec![], jsonpath: vec![]}, <>)
    },
    <s:PathSegsExpr> "." <e:JsonPathExpr> => append_jsonpath(s, e),
}

QuotedListExpr: Vec<String> = {
    SingleQuotedStringExpr => vec![<>],
    <head:QuotedListExpr> "," <elt:SingleQuotedStringExpr> => {
        let mut v = head;
        v.push(elt);
        v
    },
}

// We capture here only what follows a jsonpath only element like
// '$', '[]'. Assume dual role '*' is jsonpath here.
JsonPathExpr: Vec<String> = {
    <JsonPathEltExpr> => vec![<>],
    <h:JsonPathExpr> "." <e:JsonPathEltExpr> => {
        let mut v = h;
        v.push(e);
        v
    },
    <h:JsonPathExpr> "." <e:"ident"> => {
        let mut v = h;
        v.push(e);
        v
    },
}

// Elements we know with certainty to be jsonpath elements
JsonPathHeadExpr: String = {
    // '$' isolated root element is same as 'SELECT *'.
    // Preserve it here to distinguish from '$.*' that produces a flattened array of elements
    "$" => "$".to_string(),
    "*" => "*".to_string(),
    <i:"ident"> "[" "*" "]" => format!("{}[*]", i),
    <i:"ident"> "[" <n:"integer"> "]" => format!("{}[{}]", i, n),
    <i:"ident"> "[" <n:"integer"> "," <m:"integer"> "]" => format!("{}[{},{}]", i, n, m),
}

JsonPathEltExpr: String = {
    <JsonPathHeadExpr> => <>,
    <h:JsonPathHeadExpr> "?" "(" "@" "." <i:"ident"> <o:JpathCompOperExpr> <c:JpathConstValueExpr> ")" => {
        format!("{}?(@.{} {} {})", h, i, o.to_string(), c)
    } 
}

PathElementExpr: PathSegment = {
    <i:"ident"> => {
        PathSegment {
            name: i,
            target_ds: "".to_string(),
        }
    },
    <InverseRelExpr> => <>,
}

InverseRelExpr: PathSegment = {
    "INVERSE" "(" <tgt:"ident"> "." <rel:"ident"> ")" => {
        PathSegment {
            name: rel,
            target_ds: tgt,
        }
    }
}

SingleQuotedStringExpr: String = {
    "singlequotedstring" => <>,
}

// '{... val ... }' r1 (...) r2 (...) (...)' pattern
ValRelsExpr: ValRels = {
    <s:SingleQuotedStringExpr> <rx:SpaceSep<RelUpdateExpr>> => {
        ValRels {
            val: s,
            rels: rx,
        }
    }
}

// rs
RelClearExpr: RelUpdate = {
    <r:"ident"> => {
       RelUpdate {
          name: r,
          elts: vec![],
       } 
    }
}

// rs ('a', 1) ('b')
RelUpdateExpr: RelUpdate = {
    <r:"ident"> <rs:RelEltListExpr> => {
       RelUpdate {
          name: r,
          elts: rs,
       } 
    }
}

RelEltListExpr: Vec<RelElt> = {
    <rs:SpaceSep<RelEltExpr>> => {
        rs
    }
}

// ('a', 1) ('b')
RelEltExpr: RelElt = {
    "(" <s:CommaSep<ConstValueExpr>> ")" => {
       RelElt { segs: s } 
    }
}

JpathConstValueExpr: String = {
    "NULL" => "null".to_string(),
    "bool" => <>.to_string(),
    "number" => <>.to_string(),
    "integer" => <>.to_string(),
    "doublequotedstring" => format!("\"{}\"", <>),
}

ConstValueExpr: ConstValue = {
    "NULL" => ConstValue::Null(),
    "bool" => ConstValue::Bool(<>),
    "number" => ConstValue::Number(<>),
    "integer" => ConstValue::Number(<>),
    "singlequotedstring" => ConstValue::SingleQuotedString(<>),
}

ParseErrorExpr: SqlParseError = {
    <l:"lexerror"> => {
        SqlParseError::InvalidToken {
            location: 0,
        }
    }
}