syntax = "proto3";
package tstdata; // this becomes a rust module

// Set of sets
message SchemaPb {
  repeated DatasetPb datasets = 1;
  repeated ItemPb indexes = 2;
  repeated ItemPb rs_items = 3;
  repeated ItemPb invrs_items = 4;
  uint32 next_dataset_id = 5;
  uint32 next_item_id = 6;
}

message DatasetPb {
  uint32 id = 1;
  string name = 2;
  ItemPb descriptor = 3;
  repeated ItemPb items = 4;
}

message ItemPb {
  uint32 id = 1;
  bytes jb_content = 2;
}

message IndexPb {
  string qualified_name = 1;
  bytes capn_page = 2;
}
